Add Blake2b-160
iotaledger/crypto.rs pull request #111
Opened 2021-10-19 16:19 UTC by vuongDang

- Additional wrapper for VarBlake2b
  - Additional tests for 160 bits length
  - Update list of supported algorithms

# Description of change
Support for Blake2b for 160 bits long hash
- Write wrapper for VarBlake2b
- Generate new tests based on the previous tests of blake2b-256
- New test vectors created with b2sum using the inputs of blake2b-256 test vector
- Update list of supported algorithms 

## Links to any relevant issues

Fixes issue #110

## Type of change

Choose a type of change, and delete any options that are not relevant.

- [x] Enhancement (a non-breaking change which adds functionality)
- [x] Documentation 

## How the change has been tested

Added new tests which are an adaptation of the previous blake2b-256
Passed the `cargo test --features blake2b`

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-10-20 09:06 UTC, Wollac requested changes
Missing a `.changes` file. Please add one; consult that directory for more information.

2021-10-20 09:06 UTC, Wollac commented on README.md
> +| hashes       | BLAKE2b-160        | [`blake2b`](/src/hashes/blake2b.rs) | [rfc][BLAKE2B-RFC]         | `blake2`           | [official][BLAKE2B-TEST] | ★★★★☆ |
Let's put this before the BLAKE2b-256 so that everything is sorted

2021-10-20 18:00 UTC, Wollac approved these changes
Thanks. Looks good to me

2021-10-27 14:05 UTC, semenov-vladyslav approved these changes
Looks good

2021-10-27 14:11 UTC, merged