Cosmetics - use of standard traits over specialized implementations
iotaledger/crypto.rs pull request #126
Opened 2022-01-07 11:59 UTC by Dirk007

The changes in this PR are almost all cosmetics and for "rust"-ier feelings.
Biggest change is the standard trait `From` implementation for the Seed which removes the formerly hard constraints on Seed-creation.

## Type of change

- [X] Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

As almost everything is cosmetics, only a small test has been added to prove that the generated Seed via `From` is the same as the formerly used `from_bytes()`.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [?] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2022-05-18 13:58 UTC, semenov-vladyslav requested changes
Missing .changes file. Implement `Zeroize` for `Seed`.

2022-05-18 13:58 UTC, semenov-vladyslav commented on CHANGELOG.md
> +## \[0.9.2]
Please use .changes file instead of directly updating CHANGELOG.md.

2022-05-18 13:58 UTC, semenov-vladyslav commented on Cargo.toml
> +version = "0.9.2"
Version is updated automatically from .changes file.

2022-05-18 13:58 UTC, semenov-vladyslav commented on src/keys/slip10.rs
> +#[derive(Default)]
`Seed` contains sensitive secret bytes. It must implement `Zeroize` trait.

2023-06-13 16:30 UTC, thibault-martinez commented
Closing due to inactivity.

2023-06-13 16:30 UTC, closed without merging