Derive traits for Curve, Key, Segment and Chain
iotaledger/crypto.rs pull request #139
Opened 2022-05-17 08:00 UTC by Thoralf-M

# Description of change

Derive some traits for Curve, Key, Segment and Chain so we can use it in wallet.rs

## Type of change

- [ ] Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes

2022-05-17 14:12 UTC, semenov-vladyslav requested changes
`Hash` and `PartialEq` default instances might be insecure for secret keys.

2022-05-17 14:12 UTC, semenov-vladyslav commented on src/keys/slip10.rs
> +#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
Is it a secret key? If so then it should also derive `Zeroize`, equality should be constant time (eg. from subtle crate, `PartialEq` does not guarantee constant-time comparison), and I'm against `Hash` instances for secret keys as it might leak info about secret key.

2022-05-17 14:12 UTC, semenov-vladyslav commented on src/keys/slip10.rs
>  impl Key {
`Key::secret_key` might leak secret key bytes via local variable `il` two lines below.

2022-05-17 14:12 UTC, semenov-vladyslav commented on src/keys/slip10.rs
> +#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
`Hash` can be implemented in a secure manner via some secure HKDF construction.

2022-05-17 14:12 UTC, semenov-vladyslav commented on src/keys/slip10.rs
> +#[derive(Clone, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
Can also derive `Copy`

2022-05-17 14:38 UTC, semenov-vladyslav approved these changes
There's still an issue with secret bytes leakage via local variable. Unrelated to this PR.

2022-05-17 15:00 UTC, semenov-vladyslav approved these changes
Looks good

2022-05-18 10:33 UTC, Wollac requested changes
Missing `.changes` file. Please add one; consult that directory for more information.

Everything else looks good to me.

2022-05-19 09:03 UTC, Wollac approved these changes

2022-05-23 15:47 UTC, merged