X25519
iotaledger/crypto.rs pull request #45
Opened 2021-01-11 23:39 UTC by rootmos

2021-01-14 09:23 UTC, nothingismagick requested changes
Please update the README.md with a line in the table defining this algo.

2021-01-14 09:23 UTC, nothingismagick commented
Also, it would be nice to explain in the PR text why this is needed.

2021-01-14 10:32 UTC, Wollac commented
Yeah, I was also wondering about the same thing. What is the desired application of plain X25519?
Apart from that, it looks good to me.

2021-01-18 12:10 UTC, rootmos commented
Algorithm added to the algorithm table. Raison d'être added to PR description.

2021-01-21 09:42 UTC, Wollac commented
I am still confused with the description and the applications.
As far as I am concerned (and according to the linked RFC) X25519(k, U) computes the scalar multiplication [k]U on Curve25519.
This can then, of course, be used for Elliptic-curve Diffie–Hellman to derive a shared secret between two parties over insecure channels. I presume that this is exactly being for a "SealedBox". But what exactly is the purpose in the snapshot context which, by definition, only involves one party?

This is why I think we should make the descriptions clearer to help with this:
- Maybe write something along the lines of "Add the X25519 function that performs a scalar multiplication on the Curve25519. This is for example used when implementing Diffie-Helman key exchange."
- I don't think that overloading X25519 to use the base when U is omitted is good design. This is technically not how X25519 is defined, but just a short-cut in software which could cause confusion. `x25519_dalek` has `from` or `diffie_hellman` exactly for those different purposes of X25519. I think wrappers like this would make the usage much easier and clearer. Or what have been the considerations against using them?

2021-01-21 10:28 UTC, nothingismagick approved these changes

2021-01-21 10:28 UTC, nothingismagick commented
@Wollac - see this PR for the justification: https://github.com/iotaledger/stronghold.rs/pull/123

2021-01-21 10:44 UTC, Wollac commented
OK, fair enough if the danger of the symmetric encryption leaking the key is a consideration, I understand.

However, my explanation and design concerns still stand.

2021-01-21 10:56 UTC, Wollac commented
In addition, it might be worth considering moving this ECDHE-like key generation used for the snapshots into crypto.rs (or even inside X25519). For example, the way how the symmetric cypher (nonce) is not trivial and requires some standardization, i.e. agreement on the hash function.

2021-02-03 21:27 UTC, l1h3r commented
@Wollac would love another review on this - I've refactored into a small wrapper around the `x25519_dalek` types. for now this is minimal and doesn't include the key generation behaviour from stronghold.rs, but it removes the need for the "overloaded" x25519 function and provides a base to build on

2021-02-05 11:34 UTC, Wollac approved these changes
Thanks, looks good to me!

I've just proposed a few minor improvements to the comments. Maybe consider whether they match the usual documentation style and whether they could help.

One additional remark: With this version we no longer have the bare, byte-oriented X25519 function, exactly as specified in RFC7748. I am perfectly find with leaving it out. I might even favor this, as I think that the DH API now is safer, more readable (and maybe even a bit faster). However, this could be a potential compromise with @rootmos previous approach.

2021-02-05 11:34 UTC, Wollac commented on src/x25519.rs
> +/// An X25519 Shared Secret - the result of a Diffie-Hellman key exchange.
```suggestion
/// An X25519 Shared Secret - the result of a Diffie-Hellman key exchange.
///
/// Each party computes this from an (ephemeral) [`SecretKey`] and their counterparty's [`PublicKey`].
```

2021-02-05 11:34 UTC, Wollac commented on src/x25519.rs
> +    /// Create a new [`PublicKey`] from bytes.
```suggestion
    /// Load a [`PublicKey`] from a slice of bytes.
```

2021-02-05 11:34 UTC, Wollac commented on src/x25519.rs
> +    /// Create a new [`SecretKey`] from bytes.
```suggestion
    /// Load a [`SecretKey`] from a slice of bytes.
```

2021-02-05 11:34 UTC, Wollac commented on .changes/x25519.md
> +derivation and Diffie-Hellman exchanges using the Curve25519 curve.
```suggestion
Add X25519 Diffie-Hellman key exchange and public key derivation using the Curve25519 curve.
```

2021-02-05 11:34 UTC, Wollac commented on src/x25519.rs
> +    /// Computes a Diffie-Hellman [`SharedSecret`] with the given [`PublicKey`].
```suggestion
    /// Computes the Diffie-Hellman [`SharedSecret`] from the [`SecretKey`] and the given [`PublicKey`].
```

2021-02-05 15:53 UTC, nothingismagick commented
@l1h3r - can we keep both interfaces? The one that Gustav wrote (so that we can use that in Stronghold) and your more contemporary version?

2021-02-05 17:55 UTC, l1h3r commented
> @l1h3r - can we keep both interfaces? The one that Gustav wrote (so that we can use that in Stronghold) and your more contemporary version?

This interface supports the same patterns that were being used in both stronghold.rs PRs - [Here's an example](https://github.com/l1h3r/stronghold.rs/commit/8906ab8745b005701844ffe2a700edf6590c13a3) that updates https://github.com/iotaledger/crypto.rs/pull/45 to use the new interface.

I'm fine keeping the previous version around until @rootmos says the new interface is good for stronghold.rs

2021-02-08 16:49 UTC, lucasfernog approved these changes

2021-02-08 16:50 UTC, merged