Added Ed25519 tests
iotaledger/crypto.rs pull request #54
Opened 2021-02-17 15:48 UTC by melatron

## Description of change

* Added Malleability test case.
* Added zip215 tests.
* Added ed25519 sign.input tests.
* Removed TODO that is not needed.
* Fixes issue #19 

## Type of change

- [x] Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

All existing and new tests pass.

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-02-17 15:54 UTC, nothingismagick commented
Copying @wollac's comment from previous PR
![image](https://user-images.githubusercontent.com/35242872/108230203-c9a7e000-7140-11eb-8f7c-ba3d02ea5eea.png)

2021-02-17 15:55 UTC, nothingismagick requested changes
Please fix Clippy and add a changefile:
https://github.com/iotaledger/crypto.rs/tree/dev/.changes

2021-02-17 15:57 UTC, nothingismagick commented
For the reviewers: I have spoken with @melatron and he will setup gpg signing for his next PRs. I will sign off for this PR.

2021-02-17 15:57 UTC, nothingismagick commented on utils/test_vectors/py/ed25519_sign_transform.py
> +print("]")
Missing EOF linebreak

2021-02-17 15:58 UTC, melatron commented
@Wollac About your questions from - https://github.com/iotaledger/crypto.rs/pull/53#issuecomment-780614782

The idea of leaving the tests there is that in Rust you write integration tests in the /tests folder and unit tests under the file for the specific functionality you are testing. For the tests that are in `src/ed25519.rs ` they also use `crate::test_utils` which is not listed as a feature in the Cargo.toml file. I guess the idea is to be used only internally. Because of that I figured that these tests are more like unit tests with internal use of `test_utils`.

2021-02-17 16:02 UTC, Wollac commented
> Because of that I figured that these tests are more like unit tests with internal use of `test_utils`.

OK, fair enough. I was mainly wondering that they are kind of redundant or duplicates with the new reference test vectors. Let's leave them in then! more tests hardly ever hurt :slightly_smiling_face:

2021-02-17 16:03 UTC, Wollac approved these changes

2021-02-24 08:29 UTC, nothingismagick approved these changes

2021-02-24 08:29 UTC, merged