Add x448 key exchange
iotaledger/crypto.rs pull request #79
Opened 2021-03-24 23:17 UTC by l1h3r

# Description of change

Adds x448 key exchange for JSON web tokens used in identity.rs

## Type of change

Choose a type of change, and delete any options that are not relevant.

- [x] Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

RFC test vectors

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-12-13 09:49 UTC, felsweg-iota requested changes
Looks good to me. Fix the merge conflicts.

2021-12-13 11:27 UTC, olivereanderson commented
> Looks good to me. Fix the merge conflicts.

Should be done now.

2021-12-13 12:19 UTC, felsweg-iota approved these changes

2022-04-25 16:48 UTC, semenov-vladyslav requested changes
Three major issues that should be addressed throughout crypto.rs:

1. There should be one style-guide (is there already one?) for how to implement SecretKey/PublicKey types: naming and conversions to/from arrays/slices and common traits AsRef/From/TryFrom. Two options:
    - prepare such guide and review crypto.rs for compliance, or
    - claim it's not important and leave as is.
2. Leakage of secret bytes through temporary/local variables. Two options:
    - internally implementations use `Zeroize`, it should also be used for local variables, or
    - we can claim that such leaks are not threat enough and leave as is.
3. Trust level for third-party crates. Two options:
    - trust third-parties completely, always use latest version, no need to even run tests, or
    - do not trust third-party implementers, review not only PR to crypto.rs but also implementation code, use fixed versions of crates (eg. `x448 = "=0.6.0"`)

2022-04-25 16:48 UTC, semenov-vladyslav commented on src/keys/x448.rs
> +    pub fn from_bytes(bytes: &[u8]) -> crate::Result<Self> {
There should exist some crypto.rs-wide style-guide on how to implement such conversions: to/from array/slice own function vs trait method which can or can't fail. I'd propose the following rules:

- use standard traits as much as possible: AsRef, From/TryFrom, etc.
- use `_bytes` suffix if argument or return value is of type `[u8; N]` and use `_slice` suffix with the type is `&[u8]`
- use `try_` prefix with functions that can fail, ie. return `Result`

2022-04-25 16:48 UTC, semenov-vladyslav commented on src/keys/x448.rs
> +    pub fn as_bytes(&self) -> &[u8] {
Why not `impl AsRef<[u8]>`? Or `impl AsRef<[u8; PUBLIC_KEY_LEN]>`?

2022-04-25 16:48 UTC, semenov-vladyslav commented on src/keys/x448.rs
> +        Self::from_bytes(&bytes[..])
Why not `Ok(Self(bytes.into()))`?

2022-04-25 16:48 UTC, semenov-vladyslav commented on tests/fixtures/x448.rs
> +    // https://tools.ietf.org/html/rfc7748#section-6.1
section-6.2

2022-04-25 16:48 UTC, semenov-vladyslav commented on src/keys/x448.rs
> +        let array: [u8; SECRET_KEY_LEN] = bytes.try_into().map_err(|_| crate::Error::ConvertError {
This temporary value of `array` might leak secret key bytes. A safer way would be to construct `Self` with zero bytes as key and then do `self.0.as_mut().copy_from_slice(bytes)`. Unfortunately `x448::SecretKey` only exposes `From<[u8; 56]>` implementation which itself can leak secret key bytes.

2022-04-25 16:48 UTC, semenov-vladyslav commented on src/keys/x448.rs
> +        let mut bytes: [u8; SECRET_KEY_LEN] = [0; SECRET_KEY_LEN];
This `bytes` local variable will leak secret key bytes.

2022-05-18 11:13 UTC, Wollac commented
Seems like this PR is no longer needed. Please just re-open if it still is.

2022-05-18 11:13 UTC, closed without merging