Add P-256 signatures/key exchange
iotaledger/crypto.rs pull request #81
Opened 2021-03-25 20:22 UTC by l1h3r

# Description of change

Adds P-256 signatures and key exchange to use with JSON web tokens.

## Type of change

- [x] Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

RFC test vectors

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-12-07 13:41 UTC, JelleMillenaar commented
@felsweg-iota Can you review?

2021-12-13 09:58 UTC, felsweg-iota approved these changes
Looks good to me. Fix merge conflicts.

2022-04-26 06:40 UTC, semenov-vladyslav requested changes
Looks good, same style and secret key leakage via local variable notes.

2022-04-26 06:40 UTC, semenov-vladyslav commented on src/signatures/p256.rs
> +        self.try_sign(message)
What to do if `try_sign` fails?

2022-04-26 06:40 UTC, semenov-vladyslav commented on Cargo.toml
> +  [dependencies.p256-crate]
Didn't notice when dependencies switch to this format. Hope, no dependencies were lost

2022-04-26 06:40 UTC, semenov-vladyslav commented on src/error.rs
> +    SignatureError { alg: &'static str },
Some of these changes were proposed in other PRs

2022-04-26 06:40 UTC, semenov-vladyslav commented on src/signatures/p256.rs
> +    #[cfg(feature = "random")]
Should there also be `#[cfg_attr(docsrs, doc(cfg(feature = "random")))]`?

2022-05-18 11:14 UTC, Wollac commented
Seems like this PR is no longer needed. Please just re-open if it still is.

2022-05-18 11:14 UTC, closed without merging